name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  install_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies and test
      run: |
        cd client
        npm i
        npm test --coverage

        cd ../api
        npm i
        npm test --coverage

  build_and_deploy:
    needs: install_and_test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Deploy API to Vercel
      uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} # Optional 
          vercel-args: '--prod' # Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  # Required
          vercel-project-id: ${{ secrets.API_PROJECT_ID}} # Required 
          working-directory: ./sub-directory

    - name: Deploy Client to Vercel
      uses: amondnet/vercel-action@v20 # deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} # Optional 
          vercel-args: '--prod' # Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  # Required
          vercel-project-id: ${{ secrets.CLIENT_PROJECT_ID}} # Required 
          working-directory: ./sub-directory
